### ISSUE TITLE
Отличие

### ISSUE THREAD

**Issue by Gelezako** [tarasfrompir/alternative_market_majordomo#1]
Что за маркет, чем отличается от стандартного?

**Comment by tarasfrompir** [comment]
Можна устанавливать свои приложения если их нет в общем маркете... + все вытекающие отсюда обновление и тд

**Comment by Gelezako** [comment]
Но свои приложения так же можно устанавливать даже если их нет в маркете и так. Достаточно скопировать файлы в папки modules и templates, потом зайти в раздел "Система" -> "Mодули", там отобразится ваш модуль, после этого нажать инстал.

**Comment by tarasfrompir** [comment]
Согласен, но устанавливая по 10 модулей вручную нажав 1 кнопку и 10 раз скопировать розархивировать перенести записать удалить файлы и тд. как то не очень удобно

**Comment by Gelezako** [comment]
ага, понял)
